[package]
name = "zcash_history"
version = "0.2.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/zcash_history/"
description = "Library for Zcash blockchain history tools"

[dev-dependencies]
assert_matches = "1.3.0"
quickcheck = "0.9"

[dependencies]
byteorder = "1"
blake2 = { package = "blake2b_simd", version = "1" }
uint = "=0.9.1" # uint 0.9.2 bumps the MSRV to 1.56.1

[lib]
bench = false
